#############
### 공통 
##############
server:  
  tomcat:
    uri-encoding: UTF-8  

spring:
  application:
    name: simple-api
  profiles:
    active: local
  banner:
    location: "classpath:config/app-banner.txt"

app-info:
  build:
    version: '@project.version@'
    timestamp: '@app.build.timestamp@'

 
  
 
  
